// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorGSH.Models;

namespace RazorGSH.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250119111336_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorGSH.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPromo")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("PriceAsString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ImagePath = "image/apple.jpg",
                            IsPromo = false,
                            Name = "Apple",
                            Price = 2.5f,
                            PriceAsString = "2.5"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            ImagePath = "image/carrot.png",
                            IsPromo = false,
                            Name = "Carrot",
                            Price = 3f,
                            PriceAsString = "3.0"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ImagePath = "image/milk.jpg",
                            IsPromo = false,
                            Name = "Milk",
                            Price = 4.5f,
                            PriceAsString = "4.5"
                        });
                });

            modelBuilder.Entity("RazorGSH.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sweets"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Breadstuff"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
